#!/usr/bin/env bash
# shellcheck shell=bash

source "$(dirname -- "${BASH_SOURCE[0]}")/../bin/opsh"

PREV_HEAD=$1
shift
NEW_HEAD=$1
shift
IS_BRANCH_CHECKOUT=$1
shift

source "$SCRIPTDIR/lib.opsh"

step::000::remove-build-artifacts() {
	if [[ $PREV_HEAD != $NEW_HEAD && $IS_BRANCH_CHECKOUT = 1 ]]; then
		rm -rf dist .eslintcache
		find . -type d -name "dist" -a ! -path '*/node_modules/*' | xargs rm -rf
	fi
}

steps::run step
